name: GTS ISO
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-iso-gts:
    name: Build GTS ISOs
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: [freios]
    with:
      brand_name: ${{ matrix.brand_name }}
      stream_name: gts
