name: Latest ISO
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      brand_name:
        description: "Image Brand to Build"
        default: '["freios"]'
        type: choice
        options:
          - '["freios"]'
  schedule:
    - cron: "50 4 * * 1,2,3,4,5,6" # 4:50 UTC All But Sunday
    - cron: "50 4 * * 0" # 4:50 UTC Sunday

jobs:
  build-iso-latest:
    name: Build Latest ISOs
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ${{ fromJson(inputs.brand_name || '["freios"]') }}
    with:
      image_flavors: '["main", "nvidia", "nvidia-open"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest
